/*
 * CarPlay Hook - Main Entry Point
 *
 * Coordinates CarPlay feature modules (route guidance, cover art, etc.)
 * Called from TerminalModeBapCombi$ActiveDeviceStateListener hook.
 *
 * Usage:
 *   CarPlayHook.onActivate(context);   // CarPlay connected
 *   CarPlayHook.onDeactivate();        // CarPlay disconnected
 *
 */
package com.luka.carplay;

import com.luka.carplay.cursor.CursorController;
import com.luka.carplay.framework.CarplayBus;
import com.luka.carplay.framework.Log;
import com.luka.carplay.routeguidance.RouteGuidance;
import de.audi.app.terminalmode.IContext;
import de.audi.app.terminalmode.device.IActiveDeviceStateListener;
import de.audi.app.terminalmode.device.IDeviceManager;
import de.audi.app.terminalmode.device.TMDevice;
import de.audi.app.terminalmode.osgi.IServiceManager;
import de.audi.atip.base.IFrameworkAccess;
import de.audi.atip.interapp.combi.bap.navi.CombiBAPServiceNavi;
import org.osgi.framework.ServiceReference;

public class CarPlayHook {

    private static final String TAG = "CarPlayHook";
    /* Auto-generated by build_java.sh - do not edit manually */
    private static final String BUILD_ID = "@BUILD_ID@";

    /* State */
    private static volatile boolean active = false;
    private static volatile boolean registered = false;
    private static volatile boolean retrying = false;
    private static volatile boolean carplayRunning = false;

    private static volatile IFrameworkAccess frameworkAccess = null;

    private static Object savedContext = null;
    private static DeviceStateHandler listenerProxy = null;

    /* Live stock CombiBAPServiceNavi (actual AppConnectorNavi instance from
     * lsd.jxe). Obtained via OSGi during init. Used for direct push of
     * Map_Presentation_Status (hide flaps on VC) without relying on class
     * replacement, which doesn't shadow lsd.jxe stock classes. */
    private static volatile CombiBAPServiceNavi naviServiceRef = null;

    /* Modules (cover art handled by TerminalModeBapCombi$EventListener) */
    private static RouteGuidance routeGuidance = null;

    /* ============================================================
     * Entry Points (called from hook)
     * ============================================================ */

    /**
     * Called when CarPlay device activates.
     */
    public static void onActivate(Object context) {
        Log.i(TAG, "onActivate");
        Log.i(TAG, "Build: " + BUILD_ID);

        /* Construct CursorController BEFORE bus.start() — its ctor
         * subscribes to EVT_SCREEN_INFO, and native-side replays the
         * sticky frame the moment it sees CMD_SYNC_REQ.  If we flipped
         * the order the sticky payload would arrive at an empty
         * listener set and be silently dropped, leaving the cursor
         * stuck on its 1024x480 fallback resolution. */
        CursorController.getInstance();

        /* Kick the bus up front so every module (including cursor, which
         * does not go through tryInit) has a live channel to the hook
         * before the first CarPlay event fires. Idempotent. */
        CarplayBus.getInstance().start();

        active = true;
        savedContext = context;
        frameworkAccess = extractFramework(context);

        try {
            if (tryInit(context)) {
                Log.i(TAG, "Initialized on first attempt");
                return;
            }

            Log.i(TAG, "Starting retry thread");
            startRetryThread(context);

        } catch (Throwable t) {
            Log.e(TAG, "onActivate error", t);
            startRetryThread(context);
        }
    }

    /**
     * Called when CarPlay device deactivates.
     */
    public static void onDeactivate() {
        Log.i(TAG, "onDeactivate");
        active = false;
        carplayRunning = false;
        frameworkAccess = null;

        /* Clear cached navi service ref (no longer valid once session ends) */
        naviServiceRef = null;

        try {
            /* Stop modules */
            if (routeGuidance != null) {
                routeGuidance.stop();
                routeGuidance = null;
            }

            /* Unregister listener */
            if (savedContext != null && listenerProxy != null) {
                IDeviceManager dm = getDeviceManager(savedContext);
                if (dm != null) {
                    unregisterListener(dm);
                }
            }

        } catch (Throwable t) {
            Log.e(TAG, "onDeactivate error", t);
        } finally {
            registered = false;
            listenerProxy = null;
            savedContext = null;
            retrying = false;
            /* Drain cursor + any in-flight gesture BEFORE bus.stop() so
             * the final touch-up + CMD_CURSOR_HIDE ride the still-live
             * bus.  Wrapped in try/catch: a shutdown fault must not
             * prevent bus teardown, otherwise sockets leak. */
            try {
                CursorController.getInstance().shutdown();
            } catch (Throwable t) {
                Log.e(TAG, "cursor shutdown error", t);
            }
            /* Block up to 200 ms for the writer to actually put the
             * shutdown frames on the wire.  CarplayBus.stop() wipes
             * sendQueue[] inside closeConnectionLocked, so without
             * this flush the final touch-up + CMD_CURSOR_HIDE would
             * race the close and often lose. */
            try {
                CarplayBus.getInstance().flush(200);
            } catch (Throwable t) {
                Log.e(TAG, "bus flush error", t);
            }
            /* Tear down bus last — after every module has had a chance
             * to unsubscribe above.  stop() is idempotent. */
            CarplayBus.getInstance().stop();
        }
    }

    /* ============================================================
     * Initialization
     * ============================================================ */

    private static boolean tryInit(Object context) {
        Object naviService = getNaviService(context);
        IDeviceManager deviceManager = getDeviceManager(context);

        if (naviService == null || deviceManager == null) {
            return false;
        }

        /* Cache CombiBAPServiceNavi ref for direct Map_Presentation_Status push.
         * This is the same live stock instance BAPBridge casts and uses — by
         * going through the OSGi-registered service we hit the real stock
         * AppConnectorNavi regardless of class-replacement. */
        if (naviService instanceof CombiBAPServiceNavi) {
            naviServiceRef = (CombiBAPServiceNavi) naviService;
            Log.i(TAG, "naviServiceRef cached: " + naviService.getClass().getName());
        } else {
            Log.w(TAG, "naviService is not CombiBAPServiceNavi: " + naviService.getClass().getName());
        }

        /* Initialize route guidance module */
        routeGuidance = new RouteGuidance();
        if (!routeGuidance.init(naviService)) {
            Log.e(TAG, "RouteGuidance init failed");
            routeGuidance = null;
            return false;
        }

        /* Cover art is handled by TerminalModeBapCombi$EventListener */

        /* Register device state listener */
        if (!registerListener(deviceManager)) {
            Log.e(TAG, "Listener registration failed");
            routeGuidance = null;
            return false;
        }

        return true;
    }

    private static synchronized void startRetryThread(final Object context) {
        if (retrying) return;
        retrying = true;

        Thread t = new Thread(new Runnable() {
            public void run() {
                try {
                    int attempts = 0;
                    while (active) {
                        sleep(2000);
                        if (!active) break;

                        attempts++;
                        if (attempts % 10 == 1) {
                            Log.d(TAG, "Retry attempt " + attempts);
                        }

                        try {
                            if (active && tryInit(context)) {
                                Log.i(TAG, "Retry succeeded after " + attempts + " attempts");
                                return;
                            }
                        } catch (Throwable e) {
                            Log.d(TAG, "Retry error: " + e.getMessage());
                        }
                    }
                } finally {
                    retrying = false;
                }
            }
        }, "CarPlayHook-Retry");
        t.setDaemon(true);
        t.start();
    }

    /* ============================================================
     * Device State Callback
     * ============================================================ */

    /**
     * Called when device state changes.
     */
    public static void onDeviceStateUpdate(TMDevice device) {
        try {
            boolean carplay = device.isCarplayDevice();
            boolean activeState = device.isActive();
            boolean selected = device.isSelected();

            Log.d(TAG, "Device: carplay=" + carplay + " active=" + activeState + " selected=" + selected);

            boolean wasRunning = carplayRunning;
            carplayRunning = (carplay && activeState && selected);

            if (carplay && activeState && selected) {
                if (routeGuidance != null && !routeGuidance.isRunning()) {
                    routeGuidance.start();
                }
                /* On transition false->true: push Map_Presentation_Status
                 * with both flaps=false directly through the LIVE stock
                 * CombiBAPServiceNavi — bypasses class-replacement which
                 * doesn't shadow lsd.jxe stock classes. The stock
                 * updateMapPresentation runs on the stock instance and
                 * sends BAP FctID 54 to the cluster, hiding the flaps.
                 *
                 * largeMapView=false is safe default (normal layout); we
                 * don't know the real last value but this one matches the
                 * most common state during CarPlay (MMI not in Map tab). */
                if (!wasRunning) {
                    CombiBAPServiceNavi svc = naviServiceRef;
                    if (svc != null) {
                        try {
                            Log.i(TAG, "CarPlay active -> push updateMapPresentation(false,false,false)");
                            svc.updateMapPresentation(false, false, false);
                        } catch (Throwable t) {
                            Log.e(TAG, "updateMapPresentation push error", t);
                        }
                    } else {
                        Log.w(TAG, "naviServiceRef is null, can't push hide-flaps");
                    }
                }
            } else if (!carplay) {
                /* Actual disconnect — full teardown */
                if (routeGuidance != null && routeGuidance.isRunning()) {
                    routeGuidance.stop();
                }
            }
            /* active=false (reverse gear, camera view) or selected=false:
             * keep renderer + BAP alive. PPS data stops flowing naturally
             * while inactive, and resumes when active returns. */

        } catch (Exception e) {
            Log.e(TAG, "onDeviceStateUpdate error", e);
        }
    }

    /* ============================================================
     * State Accessors
     * ============================================================ */

    public static boolean isCarplayRunning() {
        return carplayRunning;
    }

    public static IFrameworkAccess getFrameworkAccess() {
        return frameworkAccess;
    }

    /* ============================================================
     * Service Discovery
     * ============================================================ */

    private static Object getNaviService(Object context) {
        try {
            if (!(context instanceof IContext)) {
                Log.d(TAG, "getNaviService: context is not IContext");
                return null;
            }
            IServiceManager sm = ((IContext) context).getServiceManager();
            if (sm == null) return null;

            ServiceReference[] refs = sm.getServiceReferences(CombiBAPServiceNavi.class);
            if (refs == null || refs.length == 0) return null;

            return sm.getService(refs[0]);

        } catch (Exception e) {
            Log.d(TAG, "getNaviService: " + e.getMessage());
            return null;
        }
    }

    private static IDeviceManager getDeviceManager(Object context) {
        try {
            if (!(context instanceof IContext)) return null;
            return ((IContext) context).getDeviceManager();
        } catch (Exception e) {
            Log.d(TAG, "getDeviceManager: " + e.getMessage());
            return null;
        }
    }

    private static IFrameworkAccess extractFramework(Object context) {
        try {
            if (context instanceof IContext) {
                return ((IContext) context).getFramework();
            }
        } catch (Exception e) {
            // ignore
        }
        return null;
    }

    /* ============================================================
     * Listener Registration
     * ============================================================ */

    private static boolean registerListener(IDeviceManager dm) {
        if (registered) return true;

        try {
            DeviceStateHandler handler = new DeviceStateHandler();
            dm.addActiveDeviceListener(handler);

            listenerProxy = handler;
            registered = true;
            Log.i(TAG, "Listener registered");
            return true;

        } catch (Exception e) {
            Log.e(TAG, "registerListener error", e);
            return false;
        }
    }

    private static void unregisterListener(IDeviceManager dm) {
        if (!registered || listenerProxy == null) return;

        try {
            dm.removeActiveDeviceListener(listenerProxy);
            Log.i(TAG, "Listener unregistered");

        } catch (Exception e) {
            Log.e(TAG, "unregisterListener error", e);
        }

        registered = false;
        listenerProxy = null;
    }

    /* ============================================================
     * Utilities
     * ============================================================ */

    private static void sleep(int ms) {
        try { Thread.sleep(ms); } catch (Exception e) {}
    }

    /* ============================================================
     * Status
     * ============================================================ */

    public static boolean isActive() {
        return active;
    }

    public static boolean isRegistered() {
        return registered;
    }
}
